[package]
name = "xfsrtray"
version = "1.0.2"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
x11rb = "0.12.0"
clap = { version = "4.5.1", features = ["derive"] }
# ctrlc = "3"
signal-hook = "0.3"
# dummy to trigger build 2