name: Update AUR Package Metadata

on:
  release:
    types: [published]

jobs:
  aur-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update PKGBUILD and .SRCINFO inside Arch container
        run: |
          set -e
          VERSION=${{ github.event.release.tag_name }}
          VERSION=${VERSION#v}

          # Update pkgver in PKGBUILD on host before container run
          sed -i "s/^pkgver=.*/pkgver=$VERSION/" aur/build/PKGBUILD

          # Run updpkgsums and makepkg inside Arch Linux container
          docker run --rm -v ${{ github.workspace }}/aur/build:/aur-build archlinux:latest /bin/bash -c "
            pacman -Sy --noconfirm pacman-contrib base-devel &&
            cd /aur-build &&
            updpkgsums &&
            makepkg --printsrcinfo > .SRCINFO
          "

      - name: Commit changes if any
        run: |
          git add aur/build/PKGBUILD aur/build/.SRCINFO
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: update PKGBUILD and .SRCINFO for release $VERSION"
            git push
          fi
